# Generated by Django 5.0.4 on 2024-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('medium', 'Medium'), ('expert', 'Expert')], max_length=20)),
            ],
        ),
    ]
